services:
  auth-service:
    build: ./microservices/auth-service
    ports:
      - "4000:4000"
    networks:
      - app-network
  
  middleware:
    build: ./middleware
    ports:
      - "5001:5001"
    networks:
      - app-network
    depends_on:
      - auth-service

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - middleware
      
networks:
  app-network:
    driver: bridge
