apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: maveric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: mavericacrtest.azurecr.io/auth-service:latest
        ports:
        - containerPort: 4000
        env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: JWT_SECRET
          - name: FIREBASE_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: FIREBASE_CREDENTIALS
          - name: RESEND_API_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: RESEND_API_KEY
          - name: CORS_ORIGIN
            value: http://middleware:3001
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: maveric
spec:
  selector:
    app: auth-service
  ports:
  - port: 4000
    targetPort: 4000
  type: ClusterIP
