apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: maveric
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: mavericacrtest.azurecr.io/frontend:latest
        ports:
        - containerPort: 3000
        env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: JWT_SECRET
          - name: MIDDLEWARE_URL
            value: http://middleware:3001
