apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware
  namespace: maveric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: middleware
  template:
    metadata:
      labels:
        app: middleware
    spec:
      containers:
      - name: middleware
        image: mavericacrtest.azurecr.io/middleware:latest
        ports:
        - containerPort: 3001
        env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: JWT_SECRET
          - name: AUTH_SERVICE_URL
            value: http://auth-service:4000
          - name: CORS_ORIGIN
            value: http://frontend-service:443
---
apiVersion: v1
kind: Service
metadata:
  name: middleware
  namespace: maveric
spec:
  selector:
    app: middleware
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP
