apiVersion: apps/v1
kind: Deployment
metadata:
  name: reminder-service
  namespace: maveric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reminder-service
  template:
    metadata:
      labels:
        app: reminder-service
    spec:
      containers:
      - name: reminder-service
        image: mavericacrtest.azurecr.io/reminder-service:latest
        ports:
        - containerPort: 4005
        env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: JWT_SECRET
          - name: FIREBASE_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: FIREBASE_CREDENTIALS
          - name: CORS_ORIGIN
            value: http://middleware:3001
---
apiVersion: v1
kind: Service
metadata:
  name: reminder-service
  namespace: maveric
spec:
  selector:
    app: reminder-service
  ports:
  - port: 4005
    targetPort: 4005
  type: ClusterIP
