name: Deploy to AKS

on:
  push:
    branches:
      - main
    paths:
      - 'k8s-manifests/**'
      - '.github/workflows/deploy-to-aks.yml'

  workflow_run:
    workflows: ["Build and Push to ACR"]
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      NAMESPACE: maveric

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up kubeconfig from secret
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > ~/.kube/config

      - name: Create namespace if not exists
        run: kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -

      - name: Create/Replace Kubernetes secrets from GitHub secrets
        run: |
          kubectl delete secret app-secrets -n $NAMESPACE --ignore-not-found
          kubectl create secret generic app-secrets -n $NAMESPACE \
            --from-literal=JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            --from-literal=FIREBASE_CREDENTIALS="${{ secrets.FIREBASE_CREDENTIALS }}" \
            --from-literal=RESEND_API_KEY="${{ secrets.RESEND_API_KEY }}"

      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s-manifests/

      - name: Verify Deployment
        run: kubectl get all -n $NAMESPACE
    
      - name: Get LoadBalancer IP
        id: get-ip
        run: |
          echo "🌐 Waiting for LoadBalancer external IP..."
          for i in {1..20}; do
            IP=$(kubectl get svc frontend-service -n $NAMESPACE -o jsonpath="{.status.loadBalancer.ingress[0].ip}")
            if [[ -n "$IP" ]]; then
              echo "✅ Found IP: $IP"
              echo "loadbalancer_ip=$IP" >> $GITHUB_OUTPUT
              break
            fi
            echo "⏳ Still waiting... retrying in 15s"
            sleep 15
          done
    
      - name: Show IP
        run: | 
            echo "Frontend IP is: http://${{ steps.get-ip.outputs.loadbalancer_ip }}"
        